"""empty message

Revision ID: 7a33c4b6c9ca
Revises: 0dfcd38731ef
Create Date: 2018-03-18 23:09:30.860088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a33c4b6c9ca'
down_revision = '0dfcd38731ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('user_profile', sa.Column('created_on', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user_profile', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('user_profile', sa.Column('image', sa.String(length=80), nullable=True))
    op.add_column('user_profile', sa.Column('location', sa.String(length=50), nullable=True))
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['email'])
    op.drop_column('user_profile', 'username')
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('user_profile', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    op.drop_column('user_profile', 'location')
    op.drop_column('user_profile', 'image')
    op.drop_column('user_profile', 'gender')
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'created_on')
    op.drop_column('user_profile', 'bio')
    # ### end Alembic commands ###
